 begin 
   
   for reg in (SELECT HSSATCAD.COPERATCAD, HSSATCAD.CFLAGATCAD, HSSATCAD.NNUMEATCAD , FUN_TEMPO_MOVIMENTACAO(HSSTITU.NNUMETITU,1) DATAMENOR,FUN_TEMPO_MOVIMENTACAO(HSSTITU.NNUMETITU,2) DATAMAIOR,HSSTITU.NNUMETITU,CRAZAEMPR TITULAR,        CRAZAEMPR,CCODITITU,HSSTITU.NNUMECONGE,CANS_TITU,DCONTTITU,CRAZACONGE, TRUNC(DSITUTITU) DSITUTITU,
                       CBOLETITU, NVL(NDIAWTITU,NVL(NDIAWCONGE,NDIAWEMPR)) NDIAWEMPR, NVL(HSSEMPR.NNUMEEMPR,0) NNUMEEMPR,CPERITITU,CCPERTITU,CRPCOTITU,
                       HSSTITU.NDIA_VENCI,CSITUTITU,CCAIXEMPR,SUBSTR(CARACTERISTICA_CONTRATO(HSSTITU.NNUMETITU),01,250) CARACTERISTICA, HSSTITU.NNUMEPESS, CPRIOTITU,NLIMITITU,NDIWETITU,SUBSTR(RETORNA_GRUPO_FATURAMENTO(NNUMEGRFAT),1,60) GRUPOFAT,TO_DATE(SUBSTR(RETORNA_DATA_MIN_ALT_CONTRATO(HSSTITU.NNUMETITU),1,10)) DATA_MINIMA ,TO_DATE(SUBSTR(RETORNA_DATA_MAX_ALT_CONTRATO(HSSTITU.NNUMETITU),1,10)) DATA_MAXIMA, HSSEMPR.C_CGCEMPR
                  FROM HSSTITU,HSSEMPR,HSSCONGE,(SELECT ATCAD.NNUMETITU, ATCAD.COPERATCAD, ATCAD.CFLAGATCAD, ATCAD.NNUMEATCAD
                                                   FROM HSSATCAD ATCAD,HSSSETOR,HSSATCAD TITULAR
                                                  WHERE ATCAD.NNUMETITU > 0 
                                                    AND ATCAD.NTITUUSUA = TITULAR.NNUMEUSUA(+)
                                                    AND ATCAD.CFLAGATCAD IS NULL 
                                                    AND (TITULAR.CFLAGATCAD IS NULL OR 
                                                         TITULAR.CFLAGATCAD =  'A' OR
                                                         TITULAR.CFLAGATCAD =  'D' OR
                                                         (TITULAR.CFLAGATCAD = 'R' AND TITULAR.CTIPOATCAD <> 'I')) 
                                                   AND ATCAD.NNUMESETOR = HSSSETOR.NNUMESETOR(+)) HSSATCAD
                 WHERE HSSTITU.NNUMETITU = HSSATCAD.NNUMETITU
                   --AND CRAZAEMPR LIKE '%MISSAO EVANGELICA%'
                   AND (HSSTITU.CSITUTITU NOT IN ('C','M') OR DSITUTITU >= TRUNC(SYSDATE))
                   AND HSSTITU.NNUMEEMPR = HSSEMPR.NNUMEEMPR
                   AND HSSTITU.NNUMECONGE = HSSCONGE.NNUMECONGE(+)
                   AND HSSATCAD.COPERATCAD = 'E'
                   AND HSSATCAD.CFLAGATCAD IS NULL) loop
 
   UPDATE hssatcad 
    SET CFLAGATCAD = 'E'
    WHERE nnumeatcad = reg.nnumeatcad;
    
  end loop;
end;