DECLARE 
  v_plano number;
  
cursor cr_historico(idusuario in number) is
      select nnumehplan
        from hsshplan
       where nnumeusua = idusuario
         and trunc(ddatahplan) <= sysdate
       order by ddatahplan desc, nnumehplan desc;


begin
  for reg in(SELECT DISTINCT CNOMEUSUA, HSSUSUA.NNUMEUSUA,CCODIPLAN, HSSPLAN.NNUMEPLAN
               FROM HSSUSUA,HSSPLAN,HSSTITU, HSSHPLAN
              WHERE ((CSITUUSUA = 'A' AND DINCLUSUA <= '08/10/2020') OR 
                      (CSITUUSUA <> 'A' AND DINCLUSUA <= '08/10/2020'  AND DSITUUSUA > '08/10/2020'))
                AND HSSPLAN.NNUMEPLAN = PKG_BENEFICIARIO.FUN_PLANO(HSSUSUA.NNUMEUSUA,HSSUSUA.NNUMEPLAN,'08/10/2020')
                AND HSSUSUA.NNUMETITU = HSSTITU.NNUMETITU
                AND HSSPLAN.CCODIPLAN = 1000
                AND HSSUSUA.NNUMEPLAN = 10241009 
                AND HSSHPLAN.NNUMEPLAN = 8175751
            ) loop
    
    open cr_historico(reg.nnumeusua);
      fetch cr_historico into v_plano;
    if cr_historico%found then  
      DELETE FROM HSSHPLAN
       WHERE NNUMEUSUA = reg.nnumeusua
         AND DDATAHPLAN between '20/02/2014' and '28/03/2014' OR DDATAHPLAN = '01/07/2013'
         AND NNUMEPLAN = 8175751;
    end if;
    close cr_historico;
  end loop;
end;       


/* CONSULTA REALIZADA PELO RELATORIO*/

SELECT CCODIPLAN,CDESCPLAN, CTIPOUSUA, COUNT(*) USUARIOS,  SUM(VALOR_USUARIO_VENCIMENTO(NNUMEUSUA,'08/10/2020')) TOTAL
  FROM HSSUSUA,HSSPLAN,HSSTITU
 WHERE ((CSITUUSUA = 'A' AND DINCLUSUA <= '08/10/2020') OR 
        (CSITUUSUA <> 'A' AND DINCLUSUA <= '08/10/2020'  AND DSITUUSUA > '08/10/2020'))
   AND HSSPLAN.NNUMEPLAN = PKG_BENEFICIARIO.FUN_PLANO(NNUMEUSUA,HSSUSUA.NNUMEPLAN,'08/10/2020')
   AND HSSUSUA.NNUMETITU = HSSTITU.NNUMETITU
 GROUP BY CCODIPLAN,CDESCPLAN,CTIPOUSUA,HSSTITU.NNUMEUNCOM
 ORDER BY 1,3
 
 
/* CONSULTA REALIZADA PELA TELA DE HISTORICO DE PLANO */
 SELECT * FROM HSSHPLAN
WHERE NNUMEUSUA IN (108919, 136303, 129262, 106193, 131246)
ORDER BY DDATAHPLAN,NNUMEHPLAN

--TABELA DE BACKUP
SELECT * 
  FROM BACKUP_HIST_PLANO